Specific_Url_Navigation/urls.py
from django.contrib import admin
from django.urls import path,include
import foods,electronics,cars
urlpatterns = [
    path('admin/', admin.site.urls),
    path("FOODS/",include("foods.urls")),
    path("ELECTRONICS/",include("electronics.urls")),
    path("CARS/",include("cars.urls")),
]

cars/urls.py
from django.urls import path
from cars.views import *
app_name="car"
urlpatterns = [
    path("rolls_royce/",rolls_royce,name="rolls_royce"),
]

electronics/urls.py
from django.urls import path
from electronics.views import *
app_name="Elect"

urlpatterns = [
    path("samsung/",samsung,name="samsung"),
    path("oppo/",oppo,name="oppo"),
]

foods/urls.py
from django.urls import path
from foods.views import *
app_name="foods"

urlpatterns = [
    path("sambar/",sambar,name="sambar"),
    path("biryani/",biryani,name="biryani"),
]

cars/models.py
from django.db import models

# Create your models here.

electronics/models.py
from django.db import models

# Create your models here.

foods/models.py
from django.db import models

# Create your models here.

cars/views.py
from django.shortcuts import render

# Create your views here.
def benz(request):
    return render(request,"benz.html")

def rolls_royce(request):
    return render(request,"rolls_royce.html")

electronics/views.py
from django.shortcuts import render

# Create your views here.
def samsung(request):
    return render(request,"samsung.html")


def oppo(request):
    return render(request,"oppo.html")

foods/views.py
from django.shortcuts import render

# Create your views here.
def biryani(request):
    return render(request,"biryani.html")

def sambar(request):
    return render(request,"sambar.html")

templates/biryani.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>foods_biryani</title>
    <style>
        h1,h2{
            color: chartreuse;
            background-color: crimson;
        }
        a{
            color: blue;
        }
    </style>
</head>
<body>
    <center><h1>This is foods_app biryani_function</h1>
    <h2>This is biryani_function content</h2></center>  <br><br>
    <h3>Click here for <a href="{% url 'foods:sambar' %}">foods_sambar</a> webpage</h3>
    <h3>Click here for <a href="{% url 'Elect:samsung' %}">electronics_samsung</a> webpage</h3>
    <h3>Click here for <a href="{% url 'Elect:oppo' %}">electronics_oppo</a> webpage</h3>
    <h3>Click here for <a href="{% url 'car:rolls_royce' %}">cars_rolls_royce</a> webpage</h3>


</body>
</html>

templates/oppo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>electronics_oppo</title>
    <style>
        *{
            color: rgb(125, 113, 5);
            background-color: rgb(150, 222, 215);
        }
    </style>
</head>
<body>
    <center><h1>This is electronics_app oppo_function</h1>
        <h2>This is electronics_oppo content</h2></center>
        <h3>Click here for <a href="{% url 'foods:biryani' %}">foods_biryani</a> webpage</h3>
        <h3>Click here for <a href="{% url 'Elect:samsung' %}">electronics_samsung</a> webpage</h3>
        <h3>Click here for <a href="{% url 'foods:sambar' %}">foods_sambar</a> webpage</h3>
        <h3>Click here for <a href="{% url 'car:rolls_royce' %}">cars_rolls_royce</a> webpage</h3>

        

    
</body>
</html>

templates/rolls_royce.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cars_rolls_royce</title>
    <style>
        h1,h2{
            color: rgb(3, 55, 9);
            background-color: rgb(234, 237, 54);
        }
    </style>
</head>
<body>
    <center><h1>This is cars_app rolls_royce_function</h1>
        <h2>This is cars_rolls_royce content</h2></center>  <br><br>
        <h3>Click here for <a href="{% url 'foods:biryani' %}">foods_biryani</a> webpage</h3>
        <h3>Click here for <a href="{% url 'Elect:oppo' %}">electronics_oppo</a> webpage</h3>
        <h3>Click here for <a href="{% url 'foods:sambar' %}">foods_sambar</a> webpage</h3>
        <h3>Click here for <a href="{% url 'Elect:samsung' %}">electronics_samsung</a> webpage</h3>

    
</body>
</html>

templates/sambar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>foods_sambar</title>
    <style>
        h1,h2{
            color:darkmagenta;
            background-color: aqua;
        }
        a{
            color: brown;
        }
    </style>
</head>
<body>
    <center><h1>This is foods_app sambar_function</h1>
    <h2>This is foods_sambar content</h2> <br> <br>
        <h3>Click here for <a href="{% url 'foods:biryani' %}">foods_biryani</a> webpage</h3>
        <h3>Click here for <a href="{% url 'Elect:samsung' %}">electronics_samsung</a> webpage</h3>
        <h3>Click here for <a href="{% url 'Elect:oppo' %}">electronics_oppo</a> webpage</h3>
        <h3>Click here for <a href="{% url 'car:rolls_royce' %}">cars_rolls_royce</a> webpage</h3>



</center>
    
</body>
</html>

templates/samsung.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>electronics_samsung</title>
    <style>
        h1,h2{
            color: rgb(33, 3, 48);
            background-color: rgb(66, 162, 14);
        }
    </style>
</head>
<body>
    <center><h1>This is electronics_app samsung_function</h1>
        <h2>This is electronics_samsung content</h2></center>  <br><br>
        <h3>Click here for <a href="{% url 'foods:biryani' %}">foods_biryani</a> webpage</h3>
        <h3>Click here for <a href="{% url 'Elect:oppo' %}">electronics_oppo</a> webpage</h3>
        <h3>Click here for <a href="{% url 'foods:sambar' %}">foods_sambar</a> webpage</h3>
        <h3>Click here for <a href="{% url 'car:rolls_royce' %}">cars_rolls_royce</a> webpage</h3>


    
</body>
</html>